name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main # Déclenche le workflow à chaque push sur la branche 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Exécute sur une machine virtuelle Ubuntu

    steps:
    - name: Checkout code # Étape 1: Cloner le dépôt
      uses: actions/checkout@v4

    - name: Set up Node.js # Étape 2: Configurer Node.js (Vite a besoin de Node.js)
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Utilisez la version de Node.js que votre projet utilise (ex: 18, 20, 22)
        cache: 'npm' # Ou 'yarn' si vous utilisez yarn

    - name: Install dependencies # Étape 3: Installer les dépendances du projet
      run: npm install # Ou 'yarn install' si vous utilisez yarn

    - name: Build project # Étape 4: Construire le projet (crée le dossier 'dist')
      run: npm run build # Ou 'yarn build' si vous utilisez yarn

    - name: Deploy to GitHub Pages # Étape 5: Déployer le contenu du dossier 'dist'
      uses: peaceiris/actions-gh-pages@v4 # Action GitHub tierce pour le déploiement sur Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Token d'authentification fourni par GitHub
        publish_dir: ./dist # Le dossier que Vite génère après le build
        cname: # Laissez vide si pas de domaine personnalisé, sinon mettez votre_domaine.com